version: '3'
services:
    webapp:
        image: jlot/frontend-demo-project:latest
        container_name: frontend
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 60s
        ports:
            - "8080:8080"
        links:
            - server
            
        networks:
            main:
                aliases:
                    - frontend
    server:
        image: jlot/backend-demo-project:latest
        container_name: backend
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 60s
        ports:
            - "8081:8081"
        depends_on:
            - db
            - redis
        links:
            - db
            - redis
        networks:
            main:
                aliases:
                    - backend
    db:
        image: jlot/database-demo-project:latest
        container_name: database
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
        ports:
            - "3306:3306"
        networks:
            main:
                aliases:
                    - database
    redis:
        image: redis:latest
        container_name: redis
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
        ports:
            - "6379:6379"
        networks: 
            main:
                aliases:
                    - redis
            
            
networks:
    main:
        driver: bridge